### ISSUE TITLE
ITK Header files not linked

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKOptimizationMonitor#2]
## Overview
ITK header files are not properly linked to the external module, causing build errors.

## Description
I initialized the external module with `cookiecutter` and set the ITK build directory in CMake. The initial template is able to build against ITK.

After adding new header and template files the project is no longer able to build against ITK. The external module should reference the ITK header files `itkCommand.h` and `itkExhaustiveOptimizerv4.h`, but Visual Studio indicates that these cannot be found.

I have updated dependencies in `itk-module.cmake`:
>   DEPENDS
    ITKCommon
    ITKOptimizersv4

After referencing the [ITK Software Guide](https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch9.html) and comparing with several other examples of ITK external modules I haven't been able to find the appropriate ITK CMake variables to resolve the issue. My impression is that the `itk_module_impl()` macro should link from the appropriate `include` directories but this doesn't seem to be happening.

## Expected behavior
CMake configuration and VS build execute without errors.

## Observed behavior
> cannot open source file "itkCommand.h"

> cannot open source file "itkExhaustiveOptimizerv4.h"

> Cannot open source file: 'C:\repos\itkom\test\OptimizationMonitorHeaderTest1.cxx': No such file or directory

> cannot open input file 'Optimization.lib'

@dzenanz @thewtex could you provide any insight into this issue?

**Comment by dzenanz** [comment]
Your PR #1 deletes `src/itkMinimalStandardRandomVariateGenerator.cxx`, so it should also delete https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor/blob/master/CMakeLists.txt#L4 which states that this module has a compiled part and is not a header-only module.

**Comment by tbirdso** [comment]
Thanks @dzenanz, I was misunderstanding the purpose of that variable. I've included the change in [PR 1](https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor/pull/1).

Unfortunately I'm still seeing the same linking issue. What other issues could cause ITK headers to not link correctly? Is there somewhere that modules need to be listed other than `itk-module.cmake`?

**Comment by thewtex** [comment]
If there is no longer any src/*.cxx files, then also remove *src/CMakeLists.txt*.

**Comment by tbirdso** [comment]
@thewtex [src/CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor/pull/1/files#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4) is deleted in [PR 1](https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor/pull/1).

**Comment by tbirdso** [comment]
Issue is resolved, error seems to have stemmed from a collection of 1) an improper test name, 2) a bad local ITK build, and 3) an issue with anonymous namespace Command extension class seen only on Windows platform.

~~I'm going to go ahead and close out this issue as all `build-test-cxx` checks in [PR 1](https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor/pull/1) are green and no CMake build errors are present. This issue may be reopened if failures in linking ITK during CMake configuration are observed again in the future.~~

Observed linker error again on Windows platform after uncommenting code depending on header file linkage.

**Comment by tbirdso** [comment]
Resolved! (For real this time.)

Seems the issue was potentially related to how macros were being used, still not 100% sure what the fix was. Build-cxx checks are passing now in [PR 1](https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor/pull/1).
